jenkinsci/rest-list-parameter-plugin

src/main/java/io/jenkins/plugins/restlistparam/logic/RestValueService.java
**Change**
* remove `<br/>` from all JavaDoc
**Issues**
* build was failing due to HTML `<br/>` tag present in some JavaDocs
=> fix(build): remove break line html tags from JavaDoc

src/main/java/io/jenkins/plugins/restlistparam/logic/RestValueService.java, src/main/java/io/jenkins/plugins/restlistparam/logic/ValueResolver.java, src/main/resources/io/jenkins/plugins/restlistparam/Messages.properties
**Description**
This PR fixes a rare marshaling error that could occur when the filter method was not called and the plain JsonArray from the JsonPath value resolver got returned to vlaues.
Additionally this PR adds a bit more robust filtering logic with proper error propagation back to the user.
**Changes**
* fix for a rare marshaling error
* fix for some errors caused by filtering
**Issues**
* n/a
=> fix(filtering): rare marshaling error and prevent more filtering errors

.github/release-drafter.yml, .github/workflows/releaseDrafter.yml
**Description**
This PR adds Release Drafter to this repository, so that the change-log creation process is automated.
Additionally, a GitHub workflow for releasing said drafted releases is also included.
**Changes**
* add release drafter workflow to draft releases
* add release drafter workflow to publish releases
**Issues**
* possible error in workflow definition :thinking: (:crossed_fingers: all is good, since the JSON-schema validated successfully)
=> chore(repo): add Release Drafter

README.adoc, pom.xml, src/main/resources/index.jelly
**Description**
This PR first and for most changes the URL property in the pom.xml to pinpoint the README.adoc file supposedly used by the plugin catalog page.
Additionally it updates the short description found in the plugin catalog page and adds an explicit section for the license in the readme. (in addition to already present `shileds.io` license badge)
**Changes**
* change pom `url` property to version pinned readme documentation
* change to shorten short description found in plugin catalog page
* add explicit section for License to readme (in addition to already present `shileds.io` license badge)
**Issues**
* N/A
=> chore(docu): improve presence in plugin catalog

README.adoc, pom.xml
**Description**
Hopefully fix the Plugin catalog docu once and for all -.- (:pray: It loads the readme with the next release)
**Changes**
* fixes mixed up url properties in pom.xml
* cleanup small nitpicks I had with the current readme formatting
**Issues**
* The Jenkins plugin catalog simply refused to load my readme docu (assuming the fault was me mixing up the url properties in the pom, but still :unamused:)
=> fix(docu): plugin catalog docu ... again

src/main/java/io/jenkins/plugins/restlistparam/RestListParameterDefinition.java
I was made aware of an odd caching behavior the other day at work (we use this plugin there for some builds, but I develop this in my free time xD).
The issue was that http caching was disabled, yet the values still seemed cached as some recently added values where not loaded/shown. Based on this I investigated a bit and noticed that it most likely has something to do with the lifecycle the plugin class has once it gets created and me storing the retrieved values within the class (for validation proposes before creating the parameter value).
To fix this I opted to overwrite the values list each time a request to the `getValues` gets sent, as this *should* fix it.
* fix odd caching with http caching turned off
* also adds missing `@Overwrite` for `isValid`
* n/a
=> fix(caching): odd caching behaviour with http chaching disabled 

.github/workflows/upload-release-artifact.yml, Jenkinsfile
This PR aims to migrate the Jenkins pipeline from the now *deprecated* `useAci` to  `useContainerAgent` and replaces the *deprecated* `actions/upload-release-asset` GitHub Action with a maintained alternative. 
* migrate to `useContainerAgent`in Jenkinsfile
* update `Upload release artifact` to stop using deprecated `actions/upload-release-asset`
* add sha256sum to future GitHub release assets
* n/a (just the deprecation notice by both affected components)
=> ci: general update and improvment

src/main/java/io/jenkins/plugins/restlistparam/RestListParameterDefinition.java
I the rare occasion that a re-build of a pipeline using this plugin occurred just after the Jenkins Controller was restated the value validation would always fail due to the copied parameter Definition class would have an empty list of values. (this solved itself once the Pipeline would be run once before triggering any re-build)
* fix a edge-case bug for when the parameter would be part of a re-run job
* n/a
* maybe #46 (but who knows as that had no proper description :man_shrugging:)
=> fix: failing re-build validation error after controller restarts

src/main/java/io/jenkins/plugins/restlistparam/RestListParameterDefinition.java
This PR applies a temporary fix to `doTestConfiguration` as I don't want to set a default display value expression as long xml is still supported by the plugin.
* apply temporary fix to `doTestConfiguration` when the 'default' display expr is send to it
* n/a (due to unreleased yet)
=> fix: doTestConfiguration failing due to default displayExpression

src/main/java/io/jenkins/plugins/restlistparam/logic/ValueResolver.java
This PR fixes an inefficient use of String.equals() that snuck by.
* change use pf String.equals("") to String.isEmpty()
* n/a
=> fix: inefficient string equals use

.github/workflows/codeql-analysis.yml, .github/workflows/update-release-draft.yml, .github/workflows/upload-release-artifact.yml
Slight maintenance on the current GitHub Actions deployed in this repo.
* updates Release-Drafter Action
* migrate from deprecated `adopt` JDK to its successor `temurin`
* skip caching where its not needed and use the `actions/setup-java` native one where it is
* supersedes #113
=> refactor: GitHub Actions workflows

.github/workflows/codeql-analysis.yml, .github/workflows/update-release-draft.yml, .github/workflows/upload-release-artifact.yml, pom.xml, src/main/java/io/jenkins/plugins/restlistparam/logic/ValueResolver.java
This PR applies a hacky workaround for a serialisation issue that can occur if the JSON list of values to pars was not a Map (i.e. a child JSON object) or a String.
It also takes care of some straight forward dependency bumps.
* apply "hacky" workaround for JSON serialisation issue if values are not strings 
* bump the plugin pom to 4.37
* bump various GHA to their latest version (Node16 runtime updates)
* fixes #117
=> fix: more serialisation hacks

pom.xml, src/main/resources/io/jenkins/plugins/restlistparam/RestListParameterDefinition/config.jelly, src/main/resources/io/jenkins/plugins/restlistparam/RestListParameterDefinition/index.jelly
This PR aims to enable markup support to the parameter description field.
* update the plugin requirement to a more current LTS
* add markup support for parameter description
* closes #129
=> feature: enable markup formatting in parameter description

src/main/java/io/jenkins/plugins/restlistparam/RestListParameterDefinition.java
This PR aims to rectify a logic issue in this plugins code that was not taken into account when initially creating it.
Basically, other plugins such as the [Parameterized Scheduler](https://plugins.jenkins.io/parameterized-scheduler/) only call the `createValue` method and would run into issues unless the parameter where to be initialized first from a previous call. This is due to the values list currently only initializing and filling when `getValues` gets called (i.e. when attempting to trigger a new job with the parameter).
Is this an ideal solution? No, however, in lack of a better workaround this basically ensures that the valid values list is not empty when `createValue` gets called.
* ensures there are values when attempting to create a ParameterValue and checking its validity
* …
=> fix: refresh values list if empty on param value creation

src/main/java/io/jenkins/plugins/restlistparam/RestListParameterDefinition.java
This PR aims to fix misleading success in config test, but failure on proper run.
* lookup request context when getting REST values and pass it to credential lookup
* fixes #154
=> fix: missing credential lookup context

src/main/java/io/jenkins/plugins/restlistparam/logic/RestValueService.java, src/main/java/io/jenkins/plugins/restlistparam/model/ValueOrder.java
When fetching the version from Nexus metadata, the versions are returned with ascending order. We would need to show it in descending order. The plugin doesn't allow to sort the versions in descending order correctly. because of the numeric sorting which is needing. The easiest solution was to implement a reverse sorting order.
Added an extra reverse ordering option to sort.
=> Create a reversed sorting order

src/main/java/io/jenkins/plugins/restlistparam/RestListParameterDefinition.java
When calling isValid, the value cache must be updated
Move getValues() to isValid.
fixes #205
=> Get values before validating

src/main/java/io/jenkins/plugins/restlistparam/logic/ValueResolver.java, src/test/java/io/jenkins/plugins/restlistparam/TestConst.java, src/test/java/io/jenkins/plugins/restlistparam/ValueResolverTest.java
Computing the display value should retain the original value type of the value. For example if the value is of type string but the contents of the string resemble a primitive value the some information may get lost.
Given an value list of strings `["2024.20", "2024.0"]` the json string passed to `parseDisplayValue` would be the the values `2024.20` and `2024.0`, which when re-parsed as json values will be interpreted as numbers rather than strings. This has the end effect of the display values `2024.2` and `2024` while the associated values are `2024.20` and `2024.0`.
To fix this behavior each value is "json stringified" before sent to `parseDisplayValue`. For the example above the values would be `"2024.20"` and `"2024.0"`.
=> fix: display value json input

pom.xml, src/test/java/io/jenkins/plugins/restlistparam/RestValueServiceTest.java, src/test/java/io/jenkins/plugins/restlistparam/TestConst.java, src/test/java/io/jenkins/plugins/restlistparam/ValueResolverTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
=> Migrate tests to JUnit5

src/main/webapp/css/select2-theming-patch.css
The dropdown background becomes transparent because undefined `menu-bg-color` variable for the default light theme.
Make select element containers use `input-color` as background color instead.
=> Fix menu bg transparent for the light theme
